############# Remote Mongodb Atlas #############
spring:
  data:
    mongodb:
      # Below uri works with DB admin creds stored in admin DB. It can work with normal app user too
      # uri: mongodb://admin:password@localhost:27017/Twitter-Clone?authSource=admin
      host: localhost
      port: 27017
      username: twitterUser
      password: twitterPass
      database: Twitter-Clone

#logging:
#  level:
#    org.springframework.security: DEBUG

devops:
  username: devops
  password: '$2a$12$m0C1UVjVQ/htIDKgDvK71eo/ZC3Rg6jkyOABXtrVUn0GRwDl4qLp2'

password:
  encrypt: 12